### PR TITLE
faq_altruedu_english

### PR DESCRIPTION
**Pull request by KathSupp**

### CODE REVIEW

**Review by altrupedia — CHANGES_REQUESTED** [review]
nice job! two requests: 
1) Can you split it into two commits? One adding the new file and one changing the existing?
2) can you rename dokumentation_altruedu.md -> '*_deutsch.md' in an additional third commit?
thanks!

**Comment by altrupedia** [comment]
@KathSupp I think your fork is out of sync. Can you synchronize your fork with altrupedia/docs? There should be a button on the main page of your fork. Then you will have to redo the three from commits from the beginning.

**Comment by altrupedia** [comment]
I am closing this PR and then you can create a new one, it's easier and clearer like this

**Comment by KathSupp** [comment]
Okay, I'm really not sure what you're talking about. But I'll try it out again

**Pull request closed without merging**
